#include <stdio.h>
#include <stdlib.h>
#include <jni.h>
#include <nativeStuff.h> // generated by javah via maven-native-plugin
#include "c_api.h"

JNIEXPORT jlong JNICALL Java_ml_dmlc_mxnet_jnitest_NativeStuff_helloNative
  (JNIEnv * env, jobject obj)
{
    puts("Hello from C!");
    return 10;
}

JNIEXPORT jlong JNICALL Java_ml_dmlc_mxnet_jnitest_NativeStuff_allocBuf
  (JNIEnv * env, jobject obj)
{
    int m = 10;
    int *p = (int*)malloc(sizeof(int)*m);
    for (int i = 0; i < m; i++) {
        p[i] = i * 2;
    }
    return (long)p;
}

JNIEXPORT void JNICALL Java_ml_dmlc_mxnet_jnitest_NativeStuff_printBuf
  (JNIEnv * env, jobject obj, jlong pointer)
{
    int m = 10;
    int *p = (int*)pointer;
    for (int i = 0; i < m; i++) {
        printf("%d : %d\n", i, p[i]);
    }
    free(p);
}

JNIEXPORT jlong JNICALL Java_ml_dmlc_mxnet_jnitest_ScalaNativeStuff_helloNative
  (JNIEnv * env, jobject obj)
{
    puts("Hello from Scala - C!");
    return 10;
}

JNIEXPORT jlong JNICALL Java_ml_dmlc_mxnet_jnitest_ScalaNativeStuff_allocBuf
  (JNIEnv * env, jobject obj)
{
    int m = 10;
    int *p = (int*)malloc(sizeof(int)*m);
    for (int i = 0; i < m; i++) {
        p[i] = i * 2;
    }
    return (long)p;
}

JNIEXPORT void JNICALL Java_ml_dmlc_mxnet_jnitest_ScalaNativeStuff_printBuf
  (JNIEnv * env, jobject obj, jlong pointer)
{
    int m = 10;
    int *p = (int*)pointer;
    for (int i = 0; i < m; i++) {
        printf("Scala %d : %d\n", i, p[i]);
    }
    free(p);
}

// for mxnet
JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxNDArrayCreateNone
  (JNIEnv * env, jobject obj, jobject jc)
{
    NDArrayHandle *out;
    int ret = MXNDArrayCreateNone(out);
    jclass jcClass = env->GetObjectClass(jc);
    jfieldID handlerId = env->GetFieldID(jcClass, "handler", "J");
    env->SetIntField(jc, handlerId, (long)out);
    return ret;
}

JNIEXPORT jstring JNICALL Java_ml_dmlc_mxnet_LibInfo_mxGetLastError
  (JNIEnv * env, jobject obj)
{
    char *tmpstr = "MXNetError";
    jstring rtstr = env->NewStringUTF(tmpstr);
    return rtstr;
}

JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxNDArrayFree
  (JNIEnv * env, jobject obj, jlong handle)
{
    return 0;
}
