#include <stdio.h>
#include <stdlib.h>
#include <jni.h>
#include <nativeStuff.h> // generated by javah via maven-native-plugin

JNIEXPORT jlong JNICALL Java_ml_dmlc_mxnet_jnitest_NativeStuff_helloNative
  (JNIEnv * env, jobject obj)
{
    puts("Hello from C!");
    return 10;
}

JNIEXPORT jlong JNICALL Java_ml_dmlc_mxnet_jnitest_NativeStuff_allocBuf
  (JNIEnv * env, jobject obj)
{
    int m = 10;
    int *p = (int*)malloc(sizeof(int)*m);
    for (int i = 0; i < m; i++) {
        p[i] = i * 2;
    }
    return (long)p;
}

JNIEXPORT void JNICALL Java_ml_dmlc_mxnet_jnitest_NativeStuff_printBuf
  (JNIEnv * env, jobject obj, jlong pointer)
{
    int m = 10;
    int *p = (int*)pointer;
    for (int i = 0; i < m; i++) {
        printf("%d : %d\n", i, p[i]);
    }
    free(p);
}
