#include <stdio.h>
#include <stdlib.h>
#include <jni.h>
#include "ml_dmlc_mxnet_native_c_api.h" // generated by javah
#include "c_api.h"

JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxNDArrayCreateNone(JNIEnv *env, jobject obj, jobject ndArrayHandle) {
  NDArrayHandle *out;
  int ret = MXNDArrayCreateNone(out);
  jclass ndClass = env->GetObjectClass(ndArrayHandle);
  jfieldID ptr64 = env->GetFieldID(ndClass, "ptr64", "J");
  env->SetLongField(ndArrayHandle, ptr64, (long)out);
  return ret;
}

JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxNDArrayCreate(JNIEnv *env, jobject obj,
                                                              jintArray shape,
                                                              jint ndim,
                                                              jint devType,
                                                              jint devId,
                                                              jint delayAlloc,
                                                              jobject ndArrayHandle) {
  jint *shapeArr = env->GetIntArrayElements(shape, NULL);
  NDArrayHandle *out;
  int ret = MXNDArrayCreate((mx_uint *)shapeArr, (mx_uint)ndim, devType, devId, delayAlloc, out);
  env->ReleaseIntArrayElements(shape, shapeArr, 0);
  jclass ndClass = env->GetObjectClass(ndArrayHandle);
  jfieldID ptr64 = env->GetFieldID(ndClass, "ptr64", "J");
  env->SetLongField(ndArrayHandle, ptr64, (long)out);
  return ret;
}

JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxNDArrayWaitAll(JNIEnv *env, jobject obj) {
  return MXNDArrayWaitAll();
}

JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxListFunctions(JNIEnv *env, jobject obj, jobject functions) {
  // Base.FunctionHandle.constructor
  jclass fhClass = env->FindClass("ml/dmlc/mxnet/Base$FunctionHandle");
  jmethodID fhConstructor = env->GetMethodID(fhClass,"<init>","(J)V");
  jfieldID fhClassPtr64 = env->GetFieldID(fhClass, "ptr64", "J");

  // scala.collection.mutable.ListBuffer append method
  jclass listClass = env->FindClass("scala/collection/mutable/ListBuffer");
  jmethodID listAppend = env->GetMethodID(listClass,
    "$plus$eq", "(Ljava/lang/Object;)Lscala/collection/mutable/ListBuffer;");

  // Get function list
  FunctionHandle *outArray;
  mx_uint outSize;
  int ret = MXListFunctions(&outSize, &outArray);
  for (int i = 0; i < outSize; ++i) {
    FunctionHandle fhAddr = outArray[i];
    jobject fhObj = env->NewObject(fhClass, fhConstructor, (long)fhAddr);
    env->CallObjectMethod(functions, listAppend, fhObj);
  }
  return ret;
}

// TODO: move to c_api_error.c
JNIEXPORT jstring JNICALL Java_ml_dmlc_mxnet_LibInfo_mxGetLastError(JNIEnv * env, jobject obj) {
  char *tmpstr = "MXNetError";
  jstring rtstr = env->NewStringUTF(tmpstr);
  return rtstr;
}

JNIEXPORT jint JNICALL Java_ml_dmlc_mxnet_LibInfo_mxNDArrayFree(JNIEnv * env, jobject obj, jobject ndArrayHandle) {
  // TODO
  puts("Free ndarray called");
  return 0;
}

